# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipsh < Formula
  desc "Clipboard transport over SSH — screenshots, text, or any file."
  homepage "https://github.com/pajikos/clipsh"
  version "0.4.0"
  license "MIT"

  depends_on "pngpaste" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pajikos/clipsh/releases/download/v0.4.0/clipsh_0.4.0_darwin_x86_64.tar.gz"
      sha256 "cb210af4b9075cd9a83be0d35589255021fd43f4b6f8ae41f3ec59fe79be25fe"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pajikos/clipsh/releases/download/v0.4.0/clipsh_0.4.0_darwin_arm64.tar.gz"
      sha256 "33d2f873dda9c7b39d4e365d48bf7ef45f337aa9932c5153f89eb6b6124fbbf4"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.4.0/clipsh_0.4.0_linux_x86_64.tar.gz"
      sha256 "38a784f909055fea5070f68d5818da3a94e78f597ff440ec07b51909e0cb0e84"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.4.0/clipsh_0.4.0_linux_arm64.tar.gz"
      sha256 "b929564a19fec9297ec1d02e0dc1427ad7bcd52e433049464cb2992c026aa892"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  test do
    system "#{bin}/clipsh --version"
  end
end
