# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipsh < Formula
  desc "Clipboard transport over SSH — screenshots, text, or any file."
  homepage "https://github.com/pajikos/clipsh"
  version "0.5.1"
  license "MIT"

  depends_on "pngpaste" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pajikos/clipsh/releases/download/v0.5.1/clipsh_0.5.1_darwin_x86_64.tar.gz"
      sha256 "55b71790c79c46d364caf7eb137f83aa13f141f3f3551c3de7f2ec6229efe14a"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pajikos/clipsh/releases/download/v0.5.1/clipsh_0.5.1_darwin_arm64.tar.gz"
      sha256 "66588202121d1bdcfb7506314362fbc0895a1bdf7155244c06c096c120c078a8"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.5.1/clipsh_0.5.1_linux_x86_64.tar.gz"
      sha256 "4011691a0c1a34b8c1509d58524e3d798a5fffffe96cf016e1e28a68344ef665"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.5.1/clipsh_0.5.1_linux_arm64.tar.gz"
      sha256 "805b0d5a32045f5d192cf5211eab7532cabbac75cfc9f0666aa0159f09d465b0"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  test do
    system "#{bin}/clipsh --version"
  end
end
