# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipsh < Formula
  desc "Clipboard transport over SSH — screenshots, text, or any file."
  homepage "https://github.com/pajikos/clipsh"
  version "0.3.0"
  license "MIT"

  depends_on "pngpaste" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pajikos/clipsh/releases/download/v0.3.0/clipsh_0.3.0_darwin_x86_64.tar.gz"
      sha256 "d98379691b92318977cab1dd7e77ceec85899c154d04f56431ee0c18a3bb8d60"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pajikos/clipsh/releases/download/v0.3.0/clipsh_0.3.0_darwin_arm64.tar.gz"
      sha256 "6a00829486b45e6de87baf04ba6862626242668e55f0526e5b7054c00bf0baa2"

      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.3.0/clipsh_0.3.0_linux_x86_64.tar.gz"
      sha256 "06706268d5bcc91925486828cf786ddbb4883e9abb63f85947d1a566644324e6"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pajikos/clipsh/releases/download/v0.3.0/clipsh_0.3.0_linux_arm64.tar.gz"
      sha256 "2a7382630f7a9ea4e05eccbec164954d7c436c0b464779a11995755821d48520"
      define_method(:install) do
        bin.install "clipsh"
      end
    end
  end

  test do
    system "#{bin}/clipsh --version"
  end
end
